global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'nginx'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['nginx-rtmp:80']  # Assuming NGINX exposes metrics on port 80

  - job_name: 'node-exporter'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['node_exporter:9100']  # We'll add this service later